"""A submodule for visualising emission model networks.

An EmissionModel describes a network of models connected by the operations
which turn one emission into another. This submodule draws that network, which
is the only practical way to understand a model of any size.

The whole network is drawn, not just the models reachable from a single root.
This matters because related models are roots in their own right, and expanding
a parameter variation attaches all but one of its variants as related models.

The drawing is a layered diagram, read bottom to top in the direction the
emission flows. It is built in the usual four stages:

1. Each model is placed on a row directly below the model which consumes it,
   so a grid extraction sits under whatever uses it. This keeps the diagram
   narrow; collecting every extraction onto a single bottom row instead makes
   the widest row as wide as the number of grids, which no amount of styling
   can rescue.
2. Rows are ordered by the barycentre of each model's neighbours to reduce edge
   crossings, with a placeholder standing in for each row an edge passes
   through. The placeholders reserve an empty column, so a long edge always has
   somewhere to run.
3. Columns are straightened, so chains of models line up rather than fanning.
4. Edges are routed as orthogonal elbows through the reserved columns, turning
   only in the gaps between rows. An edge therefore cannot cross a box.

Everything is measured and laid out in points, the units the boxes are drawn
in, so boxes cannot overlap regardless of the figure size. By default the
figure is sized to fit the network; if a figure size is given, the labels are
scaled down to fit it instead.

Passing layout="dot" hands the layering and placement to graphviz instead,
which is worth trying on dense networks. That needs pydot and the graphviz
binary.

Example usage::

    model.plot_emission_graph()
    model.plot_emission_graph(layout="dot")
    model.plot_emission_graph(show_variants=True)

Note that EmissionModel.plot_emission_graph is a thin wrapper around the
function of the same name here, so this module does not usually need to be
imported directly.
"""

from collections import namedtuple

import matplotlib.lines as mlines
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.font_manager import FontProperties
from matplotlib.legend_handler import HandlerPatch
from matplotlib.path import Path
from matplotlib.textpath import TextPath

from synthesizer import exceptions
from synthesizer.emission_models.base_model import EmissionModel

# The colour used for each emitter: the fill of its boxes, and a darker tone
# for their outline.
#
# The fills are what a reader actually compares, so they are what has to clear
# the colourblind and normal vision separation gates, on the all-pairs list
# since any two models can end up side by side. They are each as saturated as
# they can be while keeping their label at 4.7:1 contrast, which is why they
# are not equally far from white: gold is a light hue and can be used neat,
# where blue has to be lifted towards white to stay legible. Equal legibility
# is what makes them look like a set.
_EMITTER_COLORS = {
    "stellar": ("#936400", "#eda100"),
    "blackhole": ("#1a4a85", "#74a7e4"),
    "galaxy": ("#116c4c", "#3ab88b"),
}

# The order roots are clustered in, left to right, so a network of several
# components separates cleanly instead of interleaving
_EMITTER_ORDER = ("blackhole", "galaxy", "stellar")

# The label used for each emitter in the legend
_EMITTER_LABELS = {
    "stellar": "Stellar",
    "blackhole": "Black Hole",
    "galaxy": "Galaxy",
}

# The line style used for each kind of dependency, and its legend label
_EDGE_STYLES = {
    "transform": ((0, (4, 2)), "Transformed"),
    "combine": ("solid", "Combined"),
    "generate": ((0, (1, 2)), "Generator Scaling"),
    "scale": ((0, (5, 2, 1, 2)), "Scaled By"),
}

# The colours used for an emission reused from the emitter rather than
# generated by a model in this network
_EXTERNAL_COLORS = ("#6f757a", "#dfe1e3")

# The box shape used for each operation, so what a model does is readable at a
# glance. Each entry gives the shape, its legend label, and how much bigger the
# drawn shape is than the box it is given, which the layout has to reserve.
#
# The four silhouettes are deliberately as different from each other as the
# available shapes allow: a sharp rectangle, a pill, an oval and a scalloped
# outline. Gentler variations (a slightly rounded rectangle, say, or concave
# corners) are almost impossible to tell apart at the sizes these diagrams get
# drawn at. Shapes whose height overshoots unevenly, like an arrow, are avoided
# because an edge would no longer meet the outline where it attaches.
_OPERATION_SHAPES = {
    "extract": {
        "shape": "square",
        "label": "Extraction",
        "overshoot": (1.0, 1.0),
        "pad": 1.0,
    },
    "transform": {
        "shape": "pill",
        "label": "Transformation",
        "overshoot": (1.0, 1.0),
        # A pill's ends curve in, so it needs more room than a rectangle for
        # the label to sit clear of the outline
        "pad": 1.5,
    },
    "combine": {
        "shape": "ellipse",
        "label": "Combination",
        "overshoot": (1.42, 1.42),
        # An ellipse is drawn well outside its box, so it can afford less
        # padding, which offsets some of the room its overshoot costs
        "pad": 0.8,
    },
    "generate": {
        "shape": "roundtooth",
        "label": "Generation",
        "overshoot": (1.0, 1.0),
        # Scallops bite into the box, so this needs the most room of all
        "pad": 1.8,
    },
}

# The ink colour used for edges and text, and the lighter tone used for the
# label of a model whose emission is discarded
_INK = "#33383d"
_MUTED_INK = "#7c8288"

# The colour a box is filled with when its emission is discarded rather than
# kept. An empty box reads as "nothing is kept here" far more clearly than the
# same box drawn faded.
_DISCARDED_FILL = "#ffffff"

# The padding inside a label box, in units of the font size, before each
# shape's own factor is applied. Chosen so that every shape leaves at least
# about half the font size of clear space around its label.
_BOX_PAD = 0.7

# The style used for anything with no operation of its own, such as an emission
# reused from the emitter. It matches the pill, including its padding, since
# that is the shape it is drawn with.
_DEFAULT_SHAPE = {
    "shape": "pill",
    "label": "",
    "overshoot": (1.0, 1.0),
    "pad": 1.5,
}

# The size of a scalloped outline's teeth in a legend swatch, as a fraction of
# the swatch's height. Bigger than the proportion the boxes use, because a
# swatch is small enough that the boxes' proportion is invisible on it.
_SWATCH_TOOTH = 0.2

# The size of a scalloped outline's teeth, in units of the font size. Scaling
# these with the font rather than with the box is what lets a bigger box
# actually buy clearance: teeth proportional to the box grow with it and eat
# the room again.
_TOOTH = 0.4

# The corner radius of a label box, in units of the font size
_CORNER = 0.35

# The gaps between boxes, in units of the font size. The vertical gap is where
# the edges turn, and every edge crossing a band needs its own lane there, so
# the band grows with the number of edges which have to fit through it. A fixed
# gap leaves the busy bands unreadable and the quiet ones wastefully airy.
_HGAP = 1.5
_VGAP = 4.0
_VGAP_PER_EDGE = 0.5
_VGAP_MAX = 14.0

# The width reserved for an edge passing through a row, in units of the font
# size
_ROUTE_WIDTH = 0.6

# How far each copy of a stacked box is offset, in units of the font size. A
# per particle model is drawn as a stack, the way a flowchart marks something
# standing for many instances rather than one. Hatching says the same thing but
# has to be drawn over the label to do it.
_STACK_OFFSET = 0.38
_STACK_COPIES = 2

# How much of a box's width the edges attaching to it are fanned out over.
# Every edge leaving from the same point makes a busy network unreadable, since
# the lines then lie on top of each other for their whole length.
_PORT_SPREAD = 0.55

# How much of the band between two rows the sideways runs of edges are spread
# over. The rest is left clear so a run never grazes a box.
_LANE_SPAN = 0.7

# The margin around the network, in points
_MARGIN = 16.0

# The largest figure the auto sizing will produce, in inches. This is a
# backstop against a runaway rather than a target: a network which needs more
# room than this gets it, up to here, because shrinking the labels to fit a
# tidy figure just makes a tidy figure nobody can read.
_MAX_AUTO_SIZE = (60.0, 40.0)

# The size below which a label stops being readable. Rather than shrink past
# this to fit a figure, the figure grows.
_MIN_FONTSIZE = 6.0

# The most the gap between rows will be stretched to fill a figure taller than
# the network needs
_MAX_VGAP_STRETCH = 3.0

# The legend geometry, in units of its font size. These are passed straight to
# the legend, and reused to work out how much room it needs.
_LEGEND_HANDLE = 2.6
_LEGEND_HANDLE_HEIGHT = 1.6
_LEGEND_TEXT_PAD = 0.8
_LEGEND_COLUMN_SPACING = 1.8
_LEGEND_BORDER_PAD = 0.5
_LEGEND_AXES_PAD = 0.5
_LEGEND_SLACK = 0.6
_LEGEND_COLUMN_SLACK = 0.15

# The space left between two legend groups, in units of the font size, and the
# most columns any one group is spread over
_LEGEND_GROUP_SPACING = 3.0
_LEGEND_MAX_COLUMNS = 4

# Where each legend group sits. The two describing how models relate and which
# component they belong to are short, and sit above the network; the longer
# list of what a box itself is saying goes below it, which balances the two
# bands rather than stacking everything on top.
_LEGEND_PLACEMENT = {
    "Relationships": "top",
    "Components": "top",
    "Model Properties": "bottom",
}

# The smallest the legend text is allowed to get, whatever the labels shrink
# to. The swatches carry the shape vocabulary, so they have to stay big enough
# to tell apart.
_MIN_LEGEND_FONTSIZE = 8.0

# The prefix used for the placeholders which reserve routing columns
_ROUTE_PREFIX = "\x00route\x00"

# What one trial layout costs: where everything sits, and the room it needs
_Measured = namedtuple(
    "_Measured",
    ("positions", "sizes", "routes", "width", "height", "legend_height"),
)


def _import_networkx():
    """Import networkx, with a helpful error if it isn't installed.

    Returns:
        module:
            The networkx module.

    Raises:
        ImportError
            If networkx is not installed.
    """
    try:
        import networkx
    except ImportError:
        raise ImportError(
            "Plotting an emission model network requires networkx. Install it "
            "with 'pip install synthesizer[em-networks]' (or "
            "'pip install networkx')."
        ) from None

    return networkx


def _model_labels(model_tree, root=None):
    """Return the labels of the models to draw.

    Args:
        model_tree (EmissionModel): The model whose network is being drawn.
        root (str):
            If given, only this model and the models it depends on are drawn.
            Otherwise the whole network is drawn, including related models.

    Returns:
        set:
            The labels to draw.

    Raises:
        InconsistentArguments
            If the requested root isn't in the network.
    """
    # The whole network is everything unpacking the tree found, which includes
    # related models
    if root is None:
        return set(model_tree._models)

    # Otherwise walk down from the requested root
    if root not in model_tree._models:
        raise exceptions.InconsistentArguments(
            f"Could not find a model with the label: {root}"
        )

    labels = {root}
    pending = [model_tree[root]]
    while len(pending) > 0:
        model = pending.pop()
        for child in sorted(model._children, key=lambda m: m.label):
            if child.label not in labels:
                labels.add(child.label)
                pending.append(child)

    return labels


def _label_of(model_or_label):
    """Return the label of a model, or the string itself.

    Args:
        model_or_label (EmissionModel/str):
            The model, or a string naming an emission.

    Returns:
        str:
            The label.
    """
    if isinstance(model_or_label, EmissionModel):
        return model_or_label.label
    return model_or_label


def _dependency_edges(model):
    """Return the dependencies of a model and how it depends on them.

    Args:
        model (EmissionModel): The model to inspect.

    Returns:
        list:
            A list of (dependency_label, kind) tuples, where kind is a key of
            _EDGE_STYLES. A dependency given as a string is an emission reused
            from the emitter rather than a model, but is labelled the same way.
    """
    edges = []

    # A transformation depends on what it is applied to
    if model._is_transforming and model.apply_to is not None:
        edges.append((_label_of(model.apply_to), "transform"))

    # A combination depends on everything it combines
    if model._is_combining:
        for child in model.combine:
            edges.append((_label_of(child), "combine"))

    # A generator can depend on models for energy balance or scaling
    if model._is_generating:
        for attr in ("_intrinsic", "_attenuated", "_scaler"):
            dependency = getattr(model.generator, attr, None)
            if dependency is not None:
                edges.append((_label_of(dependency), "generate"))

    # Scaling by another emission is also a real dependency, which the old
    # plots left out entirely
    for scaler in model.scale_by:
        edges.append((_label_of(scaler), "scale"))

    return edges


def _operation_of(model):
    """Return which operation a model performs.

    Args:
        model (EmissionModel): The model to inspect.

    Returns:
        str or None:
            A key of _OPERATION_SHAPES, or None if the model somehow does
            nothing recognisable.
    """
    if model._is_extracting:
        return "extract"
    if model._is_transforming:
        return "transform"
    if model._is_combining:
        return "combine"
    if model._is_generating:
        return "generate"
    return None


def _build_graph(model_tree, root=None, show_variants=False):
    """Build the network of models as a directed graph.

    Edges run from a dependency to the model which consumes it, i.e. in the
    direction the emission flows.

    Args:
        model_tree (EmissionModel): The model whose network is being drawn.
        root (str):
            If given, only this model and the models it depends on are drawn.
        show_variants (bool):
            Whether to draw every parameter variant as its own node. By
            default each family is collapsed into one node.

    Returns:
        networkx.DiGraph:
            The network. Each node carries the attributes needed to draw it,
            and each edge carries the kind of dependency it represents.
    """
    nx = _import_networkx()

    labels = _model_labels(model_tree, root)

    # Work out what each label is drawn as. Collapsing maps every variant of a
    # model onto its pre-expansion label, which is the default: a large
    # expansion has far more models than can be read at once.
    node_of = {}
    for label in labels:
        model = model_tree[label]
        if not show_variants and model.variant_base is not None:
            node_of[label] = model.variant_base
        else:
            node_of[label] = label

    # Count how many models each node stands for, so a collapsed family can be
    # badged with its size
    counts = {}
    for node in node_of.values():
        counts[node] = counts.get(node, 0) + 1

    graph = nx.DiGraph()

    # Add the models
    for label in sorted(labels):
        model = model_tree[label]
        node = node_of[label]

        # A collapsed family is drawn once, using the first variant's styling.
        # Variants of a model differ only in a parameter value, so their
        # styling is identical anyway.
        if node in graph:
            continue

        graph.add_node(
            node,
            emitter=model.emitter,
            operation=_operation_of(model),
            is_extracting=model._is_extracting,
            is_masked=model._is_masked,
            per_particle=model.per_particle,
            save=model.save,
            count=counts[node],
            external=False,
        )

    # Add the dependencies
    for label in sorted(labels):
        model = model_tree[label]
        for dependency_label, kind in _dependency_edges(model):
            # A dependency which isn't a model in this network is an emission
            # reused from the emitter. Draw it, so the reuse is visible.
            if dependency_label not in node_of:
                if dependency_label not in graph:
                    graph.add_node(
                        dependency_label,
                        emitter=model.emitter,
                        operation=None,
                        is_extracting=False,
                        is_masked=False,
                        per_particle=False,
                        save=True,
                        count=1,
                        external=True,
                    )
                source = dependency_label
            else:
                source = node_of[dependency_label]

            target = node_of[label]

            # Collapsing can make a variant depend on itself, since the whole
            # family folds onto one node
            if source == target:
                continue

            graph.add_edge(source, target, kind=kind)

    return graph


def _swatch(
    facecolor,
    edgecolor,
    label,
    linestyle="solid",
    hatch=None,
    shape="pill",
    stacked=False,
):
    """Return a legend swatch drawn as a small box.

    Args:
        facecolor (str): The colour to fill the swatch with.
        edgecolor (str): The colour to outline the swatch with.
        label (str): The legend label.
        linestyle (str): The outline style.
        hatch (str): An optional hatch pattern.
        shape (str):
            The box shape, matching the shapes used for the operations.
        stacked (bool):
            Whether to draw the swatch as a stack of boxes, as a per particle
            model is drawn.

    Returns:
        matplotlib.patches.FancyBboxPatch:
            The swatch.
    """
    swatch = mpatches.FancyBboxPatch(
        (0.1, 0.1),
        width=0.5,
        height=0.1,
        facecolor=facecolor,
        edgecolor=edgecolor,
        linewidth=1.1,
        label=label,
        linestyle=linestyle,
        hatch=hatch,
        boxstyle="square,pad=0",
    )

    # Remembered for the legend handler, which rebuilds the box at the swatch's
    # own size to keep its shape
    swatch._shape = shape
    swatch._stacked = stacked

    return swatch


def _legend_groups(graph):
    """Build the legend entries, grouped by what they explain.

    One legend listing every encoding at once takes a lot of reading to find
    the one entry you were after. Splitting them by the question they answer,
    how models connect, which component a model belongs to, and what a box
    itself is saying, means each group can be read on its own.

    Args:
        graph (networkx.DiGraph): The network.

    Returns:
        dict:
            A dictionary of the form {<title>: [<handle>, ...]}, holding only
            the groups this network has something to say about.
    """
    kinds = {data["kind"] for _, _, data in graph.edges(data=True)}
    nodes = [data for _, data in graph.nodes(data=True)]
    emitters = {data["emitter"] for data in nodes if not data["external"]}
    operations = {data["operation"] for data in nodes}

    # How the models are connected
    connections = [
        mlines.Line2D(
            [],
            [],
            color=_INK,
            linestyle=linestyle,
            lw=0.9,
            alpha=0.75,
            label=label,
        )
        for kind, (linestyle, label) in _EDGE_STYLES.items()
        if kind in kinds
    ]

    # Which component a model acts on, carried by colour
    components = [
        _swatch(
            _EMITTER_COLORS[emitter][1],
            _EMITTER_COLORS[emitter][0],
            label=label,
        )
        for emitter, label in _EMITTER_LABELS.items()
        if emitter in emitters
    ]

    # What the box itself says: the operation, by shape, and then the state of
    # the emission it produces
    box = [
        _swatch(
            "none",
            _INK,
            label=style["label"],
            shape=style["shape"],
        )
        for operation, style in _OPERATION_SHAPES.items()
        if operation in operations
    ]

    if any(not data["save"] for data in nodes):
        box.append(_swatch("#c9ccce", _INK, label="Saved"))
        box.append(_swatch(_DISCARDED_FILL, _INK, label="Discarded"))

    if any(data["is_masked"] for data in nodes):
        box.append(
            _swatch("none", _INK, label="Masked", linestyle=(0, (3, 2)))
        )

    if any(data["per_particle"] for data in nodes):
        box.append(
            _swatch(
                "none",
                _INK,
                label="Per Particle",
                shape="round",
                stacked=True,
            )
        )

    if any(data["external"] for data in nodes):
        outline, fill = _EXTERNAL_COLORS
        box.append(
            _swatch(
                fill,
                outline,
                label="Reused Emission",
                linestyle=(0, (1, 2)),
            )
        )

    if any(data["count"] > 1 for data in nodes):
        box.append(_swatch("none", _INK, label="×N Variants"))

    groups = {
        "Relationships": connections,
        "Components": components,
        "Model Properties": box,
    }

    return {title: entries for title, entries in groups.items() if entries}


def _legend_shape(groups):
    """Work out how each legend group should be laid out.

    Args:
        groups (dict): The legend entries, grouped by title.

    Returns:
        dict:
            A dictionary of the form {<title>: (<columns>, <rows>)}.
    """
    shape = {}
    for title, entries in groups.items():
        # Two rows keeps the band above the network shallow without making any
        # group so wide that the three of them stop fitting side by side
        columns = min(_LEGEND_MAX_COLUMNS, int(np.ceil(len(entries) / 2)))
        rows = int(np.ceil(len(entries) / columns))
        shape[title] = (columns, rows)

    return shape


def _legend_entry_widths(handles):
    """Return how wide each legend entry is, in units of the font size.

    The labels are measured with the font that will draw them, since guessing
    from the character count leaves the legend clipped. Measuring in font size
    units lets the figure reserve room before a font size has been settled on.

    Args:
        handles (list): The legend handles.

    Returns:
        list:
            The width of each entry.
    """
    font = FontProperties()

    widths = []
    for handle in handles:
        label = TextPath(
            (0, 0),
            handle.get_label(),
            size=1.0,
            prop=font,
        ).get_extents()
        widths.append(_LEGEND_HANDLE + _LEGEND_TEXT_PAD + label.width)

    return widths


def _legend_group_width(title, handles, columns):
    """Return how wide one legend group needs to be, in font size units.

    Args:
        title (str): The group's title.
        handles (list): The group's entries.
        columns (int): How many columns the group is drawn in.

    Returns:
        float:
            The width needed, including the padding around the group.
    """
    entries = _legend_entry_widths(handles)

    # Each column is as wide as its widest entry, and matplotlib fills the
    # columns top to bottom rather than left to right. Measuring the widest row
    # instead leaves the group narrower than it is drawn, and the group beside
    # it then overlaps.
    rows, large = divmod(len(entries), max(columns, 1))
    width = 0.0
    start = 0
    for column in range(max(columns, 1)):
        height = rows + 1 if column < large else rows
        if height == 0:
            continue

        width += max(entries[start : start + height])
        start += height

    width += _LEGEND_COLUMN_SPACING * (max(columns, 1) - 1)

    # A long title can be wider than the entries under it, and it is drawn in
    # bold, which is wider than the same text measured plain
    heading = TextPath(
        (0, 0),
        title,
        size=1.0,
        prop=FontProperties(weight="bold"),
    ).get_extents()

    # Matplotlib's own padding does not come out exactly as modelled here, so
    # leave a little slack: the groups are placed by this measurement, and one
    # which comes out short puts the next group on top of this one.
    return (
        max(width, heading.width)
        + 2 * _LEGEND_BORDER_PAD
        + _LEGEND_SLACK
        + _LEGEND_COLUMN_SLACK * max(columns, 1)
    )


def _legend_bands(groups, shape):
    """Return the room the legends need above and below the network.

    Args:
        groups (dict): The legend entries, grouped by title.
        shape (dict): How many columns and rows each group is drawn in.

    Returns:
        widths (dict): The width each group needs, in units of the font size.
        width (float):
            The width the widest band needs, in units of the font size.
        rows (dict):
            The number of rows taken up above and below the network, keyed by
            "top" and "bottom", each including the titles.
    """
    widths = {
        title: _legend_group_width(title, handles, shape[title][0])
        for title, handles in groups.items()
    }

    width = 0.0
    rows = {"top": 0, "bottom": 0}
    for band in ("top", "bottom"):
        titles = [
            title
            for title in groups
            if _LEGEND_PLACEMENT.get(title, "top") == band
        ]
        if len(titles) == 0:
            continue

        band_width = sum(widths[title] for title in titles)
        band_width += _LEGEND_GROUP_SPACING * (len(titles) - 1)
        band_width += 2 * _LEGEND_AXES_PAD
        width = max(width, band_width)

        # The title sits on a row of its own above each group
        rows[band] = max(shape[title][1] for title in titles) + 1

    return widths, width, rows


def _extent(positions, sizes, routes=None):
    """Return the bounding box of a laid out network.

    Args:
        positions (dict): The centre of each node's box.
        sizes (dict): The box size of each node.
        routes (dict):
            The points edges are routed through. These lie outside the boxes,
            so they have to be included or an edge which swings wide of every
            box is drawn outside the axes and clipped.

    Returns:
        tuple:
            (xmin, xmax, ymin, ymax) in points.
    """
    xs = []
    ys = []
    for node, (x, y) in positions.items():
        width, height = sizes[node]
        xs.extend((x - width / 2.0, x + width / 2.0))
        ys.extend((y - height / 2.0, y + height / 2.0))

    for waypoints in (routes or {}).values():
        for x, y in waypoints:
            xs.append(x)
            ys.append(y)

    return min(xs), max(xs), min(ys), max(ys)


def _node_text(graph, node):
    """Return the text drawn in a node's box.

    Args:
        graph (networkx.DiGraph): The network.
        node (str): The node.

    Returns:
        str:
            The text, including a variant count badge where relevant.
    """
    count = graph.nodes[node]["count"]
    if count > 1:
        return f"{node}  ×{count}"
    return node


def _stack_extent(data, fontsize):
    """Return the extra room a stacked box needs, in points.

    Args:
        data (dict): The node's attributes.
        fontsize (float): The font size the labels are drawn at.

    Returns:
        float:
            The room the offset copies take up beyond the box itself.
    """
    if not data["per_particle"]:
        return 0.0

    return _STACK_COPIES * _STACK_OFFSET * fontsize


def _shape_spec(operation):
    """Return how an operation's node is drawn.

    Args:
        operation (str): A key of _OPERATION_SHAPES, or None.

    Returns:
        dict:
            The shape name, the (width, height) factors the drawn shape needs
            beyond the box it is given, and the factor to scale the label
            padding by (a shape which curves or bites into its box needs more
            room around the label than a plain rectangle).
    """
    return _OPERATION_SHAPES.get(operation, _DEFAULT_SHAPE)


def _box_sizes(graph, fontsize):
    """Measure the box drawn for each node, in points.

    The text is measured with the font that will draw it rather than estimated,
    so the layout can guarantee boxes don't overlap.

    Args:
        graph (networkx.DiGraph): The network.
        fontsize (float): The font size the labels will be drawn at.

    Returns:
        dict:
            A dictionary of the form {<node>: (width, height)} in points.
    """
    # Measure with the font that will actually draw the labels, so the boxes
    # are sized for the real text rather than an estimate
    font = FontProperties()

    sizes = {}
    for node in graph.nodes:
        text = _node_text(graph, node)
        extents = TextPath(
            (0, 0),
            text,
            size=fontsize,
            prop=font,
        ).get_extents()

        # Use a fixed height for every box so rows line up, rather than letting
        # descenders and capitals change it label by label
        operation = graph.nodes[node]["operation"]
        pad = 2.0 * _BOX_PAD * _shape_spec(operation)["pad"] * fontsize
        width = extents.width + pad
        height = fontsize * 1.05 + pad

        # Some shapes are drawn outside the box they are given, so the layout
        # has to reserve the room they will really take up, as does the stack a
        # per particle model is drawn as
        wide, tall = _shape_spec(operation)["overshoot"]
        stack = _stack_extent(graph.nodes[node], fontsize)
        sizes[node] = (width * wide + stack, height * tall + stack)

    return sizes


def _assign_layers(graph):
    """Assign each node to a row, packed as close to its consumers as possible.

    A node sits on the row directly below the lowest model which consumes it.
    Nodes nothing depends on end up on the top row, and a grid extraction ends
    up directly beneath whatever uses it rather than on a shared bottom row.
    That keeps the diagram narrow: aligning every extraction instead makes the
    widest row as wide as the number of grids.

    Args:
        graph (networkx.DiGraph): The network.

    Returns:
        dict:
            A dictionary of the form {<node>: <row>}, counting up from zero at
            the bottom.

    Raises:
        InconsistentArguments
            If the network contains a cycle.
    """
    nx = _import_networkx()

    try:
        order = list(nx.topological_sort(graph))
    except nx.NetworkXUnfeasible:
        raise exceptions.InconsistentArguments(
            "The emission model network contains a cycle, so it cannot be "
            "drawn as layers."
        ) from None

    # Walk consumers before their dependencies, so a node can be placed just
    # below the lowest consumer it has
    layers = {}
    for node in reversed(order):
        consumers = list(graph.successors(node))
        if len(consumers) == 0:
            layers[node] = 0
        else:
            layers[node] = min(layers[consumer] for consumer in consumers) - 1

    # Shift so the bottom row is row zero
    lowest = min(layers.values())

    return {node: layer - lowest for node, layer in layers.items()}


def _insert_routing_nodes(graph, layers):
    """Add placeholders reserving a column for each edge which spans rows.

    An edge between rows that aren't adjacent has to get past the rows in
    between. Giving it a placeholder on each of those rows reserves an empty
    column for it during ordering and placement, so the edge always has
    somewhere to run and can never cross a box.

    Args:
        graph (networkx.DiGraph): The network.
        layers (dict): The row of each node.

    Returns:
        routing (networkx.DiGraph):
            The network with long edges replaced by chains of placeholders.
        routing_layers (dict): The row of every node in that network.
        chains (dict):
            A dictionary of the form {(source, target): [<placeholder>, ...]}
            giving the placeholders along each long edge, bottom to top.
    """
    nx = _import_networkx()

    routing = nx.DiGraph()

    # Carry the node attributes over, since the ordering needs to know which
    # emitter each model belongs to in order to cluster them
    routing.add_nodes_from(graph.nodes(data=True))
    routing_layers = dict(layers)
    chains = {}

    for source, target in sorted(graph.edges):
        # An edge between adjacent rows needs no help
        if layers[target] - layers[source] <= 1:
            routing.add_edge(source, target)
            continue

        # Chain a placeholder through every row the edge passes
        chain = []
        previous = source
        for layer in range(layers[source] + 1, layers[target]):
            placeholder = f"{_ROUTE_PREFIX}{source}\x00{target}\x00{layer}"
            routing.add_node(placeholder)
            routing_layers[placeholder] = layer
            routing.add_edge(previous, placeholder)
            chain.append(placeholder)
            previous = placeholder

        routing.add_edge(previous, target)
        chains[(source, target)] = chain

    return routing, routing_layers, chains


def _emitter_rank(graph, node):
    """Return where a node's emitter sits in the left to right order.

    Args:
        graph (networkx.DiGraph): The network.
        node (str): The node.

    Returns:
        float:
            The rank, with unknown emitters (and routing placeholders) landing
            in the middle so they don't disturb the clustering.
    """
    if node not in graph.nodes:
        return (len(_EMITTER_ORDER) - 1) / 2.0

    emitter = graph.nodes[node].get("emitter")
    if emitter in _EMITTER_ORDER:
        return float(_EMITTER_ORDER.index(emitter))

    return (len(_EMITTER_ORDER) - 1) / 2.0


def _order_rows(graph, layers, nsweeps=8):
    """Order the nodes within each row to reduce edge crossings.

    Each node is repeatedly moved to the average position of its neighbours in
    the adjacent row, which is the barycentre heuristic. Sweeps alternate
    direction so ordering information propagates both up and down the network.

    Args:
        graph (networkx.DiGraph):
            The network, including any routing placeholders.
        layers (dict): The row of each node.
        nsweeps (int): How many ordering sweeps to run.

    Returns:
        dict:
            A dictionary of the form {<row>: [<node>, ...]} giving the order of
            the nodes in each row.
    """
    # Group the nodes by row, ordered by emitter and then by label, so the
    # result doesn't depend on the order the graph was built in and the
    # components start out clustered
    rows = {}
    for node in sorted(
        layers,
        key=lambda node: (_emitter_rank(graph, node), node),
    ):
        rows.setdefault(layers[node], []).append(node)

    if len(rows) < 2:
        return rows

    row_numbers = sorted(rows)

    # The top row holds every model nothing depends on. Clustering those by
    # emitter keeps the black hole models, galaxy models and stellar models in
    # their own regions rather than interleaved, and the rows below follow them
    # because they are ordered by where their consumers sit.
    top_row = row_numbers[-1]

    for sweep in range(nsweeps):
        # Alternate between using the row below and the row above as the
        # reference, so ordering propagates in both directions
        downward = sweep % 2 == 0
        sweep_rows = row_numbers if downward else row_numbers[::-1]

        for row in sweep_rows:
            reference = row - 1 if downward else row + 1
            if reference not in rows:
                continue

            positions = {node: i for i, node in enumerate(rows[reference])}

            def _barycentre(node, positions=positions, downward=downward):
                """Return the mean position of a node's neighbours."""
                neighbours = (
                    graph.predecessors(node)
                    if downward
                    else graph.successors(node)
                )
                indices = [
                    positions[neighbour]
                    for neighbour in neighbours
                    if neighbour in positions
                ]

                # A node with no neighbours in the reference row keeps its
                # current position
                if len(indices) == 0:
                    return rows[row].index(node)

                return float(np.mean(indices))

            # Sort by barycentre, breaking ties on the label so the layout is
            # reproducible. The top row keeps its emitter clustering, with the
            # barycentre only ordering within each emitter's region.
            if row == top_row:
                rows[row] = sorted(
                    rows[row],
                    key=lambda node: (
                        _emitter_rank(graph, node),
                        _barycentre(node),
                        node,
                    ),
                )
            else:
                rows[row] = sorted(
                    rows[row],
                    key=lambda node: (_barycentre(node), node),
                )

    return rows


def _assign_coordinates(
    graph, rows, sizes, fontsize, loads=None, vgap_scale=1.0, nsweeps=6
):
    """Give every node a position, in points.

    Nodes are first packed along their row, which is what guarantees they can't
    overlap, and then nudged towards their neighbours in the rows above and
    below. The nudging is what straightens chains of models into columns rather
    than leaving them fanned across the diagram.

    Args:
        graph (networkx.DiGraph):
            The network, including any routing placeholders.
        rows (dict): The order of the nodes in each row.
        sizes (dict):
            The box size of each node, in points. Routing placeholders are
            absent and are treated as narrow gaps.
        fontsize (float): The font size the labels will be drawn at.
        loads (dict):
            How many edges cross the band above each row, which sets how much
            room that band needs.
        vgap_scale (float):
            A factor applied to the gap between rows. Used to spread the
            network over the height available rather than leaving it in a band.
        nsweeps (int): How many straightening sweeps to run.

    Returns:
        dict:
            The centre of each node's box, of the form {<node>: (x, y)}.
    """
    hgap = _HGAP * fontsize
    route_width = _ROUTE_WIDTH * fontsize
    loads = loads or {}

    def _vgap(row):
        """Return the room to leave above a row, in points."""
        # Each edge beyond the first needs its own lane in this band
        lanes = max(0, loads.get(row, 1) - 1)
        gap = min(_VGAP_MAX, _VGAP + _VGAP_PER_EDGE * lanes)

        return gap * fontsize * vgap_scale

    def _width(node):
        """Return the horizontal room a node needs."""
        if node in sizes:
            return sizes[node][0]
        return route_width

    def _height(node):
        """Return the vertical room a node needs."""
        if node in sizes:
            return sizes[node][1]
        return 0.0

    # Stack the rows bottom to top, each as tall as its tallest box, leaving
    # each band as much room as the edges crossing it need
    row_numbers = sorted(rows)
    ys = {}
    y = 0.0
    for row in row_numbers:
        height = max((_height(node) for node in rows[row]), default=0.0)
        ys[row] = y + height / 2.0
        y += height + _vgap(row)

    # Pack each row, centred on zero
    xs = {}
    for row in row_numbers:
        nodes = rows[row]
        total = sum(_width(node) for node in nodes) + hgap * (len(nodes) - 1)
        x = -total / 2.0
        for node in nodes:
            width = _width(node)
            xs[node] = x + width / 2.0
            x += width + hgap

    # Straighten: nudge each node towards its neighbours, then re-pack the row
    # so nothing has been pushed into anything else
    for sweep in range(nsweeps):
        downward = sweep % 2 == 0
        sweep_rows = row_numbers if downward else row_numbers[::-1]

        for row in sweep_rows:
            nodes = rows[row]

            # Where each node would like to be, based on the row it's being
            # aligned to
            desired = []
            for node in nodes:
                neighbours = (
                    list(graph.predecessors(node))
                    if downward
                    else list(graph.successors(node))
                )
                aligned = [xs[n] for n in neighbours if n in xs]
                desired.append(np.mean(aligned) if aligned else xs[node])

            # Move each node halfway towards where it wants to be, then
            # repair any overlap that created. The repair alternates
            # direction: fixing overlaps only by pushing right drags every row
            # rightwards and leaves gaps behind which never close, which is
            # what spreads a diagram out.
            placed = [
                x + 0.5 * (want - x)
                for x, want in zip((xs[node] for node in nodes), desired)
            ]

            separations = [
                _width(nodes[i]) / 2.0 + hgap + _width(nodes[i + 1]) / 2.0
                for i in range(len(nodes) - 1)
            ]

            for _ in range(2):
                # Push right where boxes have collided
                for i in range(1, len(nodes)):
                    placed[i] = max(
                        placed[i],
                        placed[i - 1] + separations[i - 1],
                    )

                # Then pull back left wherever there's slack to close
                for i in range(len(nodes) - 2, -1, -1):
                    placed[i] = min(
                        placed[i],
                        placed[i + 1] - separations[i],
                    )

            for node, x in zip(nodes, placed):
                xs[node] = x

    # Centre the whole diagram, since the rows have drifted independently
    centre = (
        min(xs[node] - _width(node) / 2.0 for node in xs)
        + max(xs[node] + _width(node) / 2.0 for node in xs)
    ) / 2.0
    xs = {node: x - centre for node, x in xs.items()}

    return {
        node: (xs[node], ys[layer])
        for layer, nodes in rows.items()
        for node in nodes
    }


def _dot_coordinates(graph, sizes, fontsize):
    """Lay the network out using graphviz, in points.

    Args:
        graph (networkx.DiGraph): The network.
        sizes (dict): The box size of each node, in points.
        fontsize (float): The font size the labels will be drawn at.

    Returns:
        dict:
            The centre of each node's box, of the form {<node>: (x, y)}.

    Raises:
        ImportError
            If pydot or the graphviz binary are not available.
    """
    nx = _import_networkx()

    # Tell graphviz exactly how big each box is, in inches, so it reserves room
    # for the labels rather than laying out points and leaving them to overlap
    sized = graph.copy()
    for node in sized.nodes:
        width, height = sizes[node]
        sized.nodes[node].clear()
        sized.nodes[node].update(
            shape="box",
            fixedsize="true",
            width=(width + _HGAP * fontsize) / 72.0,
            height=(height + _VGAP * fontsize) / 72.0,
        )
    for edge in sized.edges:
        sized.edges[edge].clear()

    try:
        raw = nx.nx_pydot.graphviz_layout(sized, prog="dot")
    except Exception as e:
        raise ImportError(
            "The 'dot' layout needs pydot and the graphviz binary. Install "
            "them with 'pip install synthesizer[em-networks]' and your "
            "system package manager (e.g. 'brew install graphviz'). "
            f"The underlying error was: {e}"
        ) from None

    # graphviz works in points too, but puts the nodes with no dependencies at
    # the top, so flip the vertical axis to match our own layout
    highest = max(y for _, y in raw.values())

    return {node: (x, highest - y) for node, (x, y) in raw.items()}


def _band_loads(graph, layers):
    """Count the edges which have to get through each band between rows.

    Every one of them turns sideways in that band and needs a lane of its own,
    so this is what decides how much room the band needs.

    Args:
        graph (networkx.DiGraph): The network.
        layers (dict): The row of each node.

    Returns:
        dict:
            A dictionary of the form {<row>: <count>} giving the number of
            edges crossing the band directly above each row.
    """
    loads = {}
    for source, target in graph.edges:
        for row in range(layers[source], layers[target]):
            loads[row] = loads.get(row, 0) + 1

    return loads


def _layout(graph, layout, fontsize, vgap_scale=1.0):
    """Place every node and route every edge, in points.

    Args:
        graph (networkx.DiGraph): The network.
        layout (str): Either "layered" or "dot".
        fontsize (float): The font size the labels will be drawn at.
        vgap_scale (float): A factor applied to the gap between rows.

    Returns:
        positions (dict): The centre of each node's box.
        sizes (dict): The box size of each node.
        routes (dict):
            The points each edge should be routed through, of the form
            {(source, target): [(x, y), ...]}. Empty for an edge which can go
            straight from one row to the next.
    """
    sizes = _box_sizes(graph, fontsize)

    if layout == "dot":
        # graphviz places the nodes so straight edges work, so there's nothing
        # to route around
        return _dot_coordinates(graph, sizes, fontsize), sizes, {}

    layers = _assign_layers(graph)
    routing, routing_layers, chains = _insert_routing_nodes(graph, layers)
    rows = _order_rows(routing, routing_layers)
    placed = _assign_coordinates(
        routing,
        rows,
        sizes,
        fontsize,
        loads=_band_loads(graph, layers),
        vgap_scale=vgap_scale,
    )

    # Split the placeholders back out as the points to route each long edge
    # through
    positions = {node: placed[node] for node in graph.nodes}
    routes = {
        edge: [placed[placeholder] for placeholder in chain]
        for edge, chain in chains.items()
    }

    return positions, sizes, routes


def _fit(
    graph,
    layout,
    fontsize,
    figsize,
    legend_width,
    legend_rows,
    min_fontsize,
):
    """Lay the network out, sizing the figure or the labels so it fits.

    The layout is done in points so it can be drawn with one data unit per
    point, which is what stops the boxes overlapping. With no figure size
    requested the figure is sized to the network, up to a maximum; beyond that,
    and whenever a figure size is given, the labels shrink until the network
    fits.

    Args:
        graph (networkx.DiGraph): The network.
        layout (str): Either "layered" or "dot".
        fontsize (float): The requested font size.
        figsize (tuple):
            The requested figure size in inches, or None to size it to fit.
        legend_width (float):
            How wide the legend needs to be, in units of the font size.
        legend_rows (dict):
            How many rows the legends occupy above and below the network, keyed
            by "top" and "bottom".
        min_fontsize (float):
            The size below which labels stop being readable. The figure is
            grown rather than shrinking the labels past this.

    Returns:
        positions (dict): The centre of each node's box, in points.
        sizes (dict): The box size of each node, in points.
        routes (dict): The points each edge should be routed through.
        fontsize (float):
            The font size to draw at, which may be smaller than requested.
        figsize (tuple): The figure size to use, in inches.
        limits (tuple): The axis limits in points, as (xmin, xmax, ymin, ymax).

    Raises:
        InconsistentArguments
            If an unknown layout is requested.
    """
    if layout not in ("layered", "dot"):
        raise exceptions.InconsistentArguments(
            f"Unknown layout '{layout}'. Must be 'layered' or 'dot'."
        )

    def _measure(size, vgap_scale=1.0):
        """Lay the network out at a font size and report the room it needs."""
        positions, sizes, routes = _layout(
            graph,
            layout,
            size,
            vgap_scale=vgap_scale,
        )
        xmin, xmax, ymin, ymax = _extent(positions, sizes, routes)

        # The legends have a minimum size of their own, so the room they need
        # has to be worked out at the size they will really be drawn
        legend_size = max(size, _MIN_LEGEND_FONTSIZE)
        legend_height = sum(legend_rows.values()) * 2.9 * legend_size

        # A small network must still be wide enough for its legend
        width = max(xmax - xmin, legend_width * legend_size) + 2 * _MARGIN
        height = (ymax - ymin) + 2 * _MARGIN + legend_height

        return _Measured(
            positions, sizes, routes, width, height, legend_height
        )

    measured = _measure(fontsize)

    # With no figure size requested, the figure is simply made big enough for
    # the network at the font size asked for. Labels stay the size they were
    # asked to be and the figure grows instead, so a large network stays as
    # readable as a small one: you look at more of it rather than at smaller
    # writing.
    auto_size = figsize is None
    if auto_size:
        figsize = (
            min(measured.width, _MAX_AUTO_SIZE[0] * 72.0) / 72.0,
            min(measured.height, _MAX_AUTO_SIZE[1] * 72.0) / 72.0,
        )

    # A network too big to fit even the largest figure has to shrink its labels
    # past the readable floor. Growing the figure instead has no limit, and an
    # image beyond about 65,000 pixels on a side cannot be saved at all, so an
    # enormous network is drawn small rather than not drawn.
    if (
        measured.width > _MAX_AUTO_SIZE[0] * 72.0
        or measured.height > _MAX_AUTO_SIZE[1] * 72.0
    ):
        min_fontsize = 0.0

    # Shrink the labels until the network fits, but never past the point where
    # they stop being readable. The layout scales with the font size, so one
    # pass gets close and a couple more clean up the difference.
    for _ in range(4):
        scale = min(
            1.0,
            figsize[0] * 72.0 / measured.width,
            figsize[1] * 72.0 / measured.height,
        )
        if scale >= 0.999:
            break

        # Legibility wins over the requested figure size: below this the labels
        # are there in name only, and the figure grows to fit them instead
        if fontsize * scale < min_fontsize:
            scale = min_fontsize / fontsize
            if scale >= 1.0:
                break

        fontsize *= scale
        measured = _measure(fontsize)

        if np.isclose(fontsize, min_fontsize):
            break

    # Shrinking the labels shrinks the network with them, so an automatically
    # sized figure has to be re-fitted afterwards. Without this a wide network
    # is drawn as a thin band in a tall, mostly empty figure.
    #
    # A figure size which was asked for is also grown if the network cannot fit
    # inside it with readable labels, since a plot too small to read is no use
    # whatever size it was asked to be.
    # The growth is bounded by the same maximum, for the same reason: a figure
    # which cannot be saved is no use. A figure size which asks for more than
    # the maximum is honoured, it is only the automatic growth which stops.
    grown = (
        min(measured.width / 72.0, _MAX_AUTO_SIZE[0]),
        min(measured.height / 72.0, _MAX_AUTO_SIZE[1]),
    )
    if auto_size:
        figsize = grown
    else:
        figsize = (
            max(figsize[0], grown[0]),
            max(figsize[1], grown[1]),
        )

    width_pts = figsize[0] * 72.0
    height_pts = figsize[1] * 72.0

    # Shrinking the labels to fit the width can leave the network as a band in
    # a much taller figure. Spread the rows over the space instead: the boxes
    # stay the size they are, only the gaps between rows grow.
    # Only the gaps grow, not the boxes, so the stretch needed can't be found
    # in one step. A few iterations converge on filling the space.
    stretch = 1.0
    for _ in range(4):
        available = height_pts - 2 * _MARGIN - measured.legend_height
        content = measured.height - 2 * _MARGIN - measured.legend_height
        if content <= 0.0 or available <= content * 1.02:
            break

        stretch = min(_MAX_VGAP_STRETCH, stretch * available / content)
        measured = _measure(fontsize, vgap_scale=stretch)

        if stretch >= _MAX_VGAP_STRETCH:
            break

    # Limits in points, so a data unit is a point and the boxes are drawn at
    # exactly the size the layout assumed. The network is centred, with the
    # legend space left at the top.
    xmin, xmax, ymin, ymax = _extent(
        measured.positions, measured.sizes, measured.routes
    )
    spare = max(
        0.0,
        height_pts - (ymax - ymin) - 2 * _MARGIN - measured.legend_height,
    )
    xcentre = (xmin + xmax) / 2.0

    # Leave the band below the network clear for the legends drawn there, and
    # split whatever is left over evenly above and below
    legend_size = max(fontsize, _MIN_LEGEND_FONTSIZE)
    below = legend_rows["bottom"] * 2.9 * legend_size
    ybottom = ymin - _MARGIN - below - spare / 2.0
    limits = (
        xcentre - width_pts / 2.0,
        xcentre + width_pts / 2.0,
        ybottom,
        ybottom + height_pts,
    )

    return (
        measured.positions,
        measured.sizes,
        measured.routes,
        fontsize,
        figsize,
        limits,
    )


def _drawn_box(data, size, fontsize):
    """Return the size of the box a node is actually drawn at, in points.

    The size the layout reserves also covers whatever the shape draws outside
    its box and the offset copies of a stack, so the box itself is smaller.

    Args:
        data (dict): The node's attributes.
        size (tuple): The room reserved for the node.
        fontsize (float): The font size the labels are drawn at.

    Returns:
        tuple:
            The (width, height) of the box to draw.
    """
    wide, tall = _shape_spec(data["operation"])["overshoot"]
    stack = _stack_extent(data, fontsize)

    return ((size[0] - stack) / wide, (size[1] - stack) / tall)


def _box_style(shape, height, tooth):
    """Return the matplotlib box style drawing a shape at a given height.

    Args:
        shape (str): The shape name.
        height (float): The height of the box.
        tooth (float): How deep a scalloped outline's teeth are.

    Returns:
        str:
            The matplotlib box style.
    """
    if shape == "square":
        return "square,pad=0"

    # A pill is a rounded box whose corners are as round as they can get
    if shape == "pill":
        return f"round,pad=0,rounding_size={height / 2.0}"

    if shape == "ellipse":
        return "ellipse,pad=0"

    if shape == "roundtooth":
        return f"roundtooth,pad=0,tooth_size={tooth}"

    return f"round,pad=0,rounding_size={height / 4.0}"


def _node_outlines(graph, positions, sizes, fontsize):
    """Return the outline of every node's box, in points.

    Args:
        graph (networkx.DiGraph): The network.
        positions (dict): The centre of each node's box.
        sizes (dict): The box size of each node.
        fontsize (float): The font size the labels are drawn at.

    Returns:
        dict:
            A dictionary of the form {<node>: <matplotlib.path.Path>}.
    """
    outlines = {}
    for node, (x, y) in positions.items():
        data = graph.nodes[node]
        box_width, box_height = _drawn_box(data, sizes[node], fontsize)

        # Edges attach to the box itself, not to the copies of a stack behind
        # it, so this has to match where the box is actually drawn
        offset = _STACK_OFFSET * fontsize
        copies = _STACK_COPIES if data["per_particle"] else 0

        patch = mpatches.FancyBboxPatch(
            (
                x - box_width / 2.0,
                y - box_height / 2.0 + copies * offset,
            ),
            box_width,
            box_height,
            boxstyle=_box_style(
                _shape_spec(data["operation"])["shape"],
                box_height,
                _TOOTH * fontsize,
            ),
        )
        outlines[node] = patch.get_path().transformed(
            patch.get_patch_transform()
        )

    return outlines


def _edge_ports(graph, positions, sizes):
    """Spread the point each edge attaches at along the edge of its box.

    Every edge leaving a box from the same point, and every edge arriving at
    one, makes a busy network very hard to follow: the lines lie on top of each
    other for their whole length. Fanning the attachment points out along the
    box separates them from the start.

    Args:
        graph (networkx.DiGraph): The network.
        positions (dict): The centre of each node's box.
        sizes (dict): The box size of each node.

    Returns:
        tuple:
            Two dictionaries keyed by edge, giving the horizontal position the
            edge leaves its source at and arrives at its target at.
    """
    leaving = {}
    arriving = {}

    for node in graph.nodes:
        centre_x = positions[node][0]

        # The room to fan out over, kept well inside the box so a port never
        # lands on a corner or on the curve of a rounded end
        spread = sizes[node][0] * _PORT_SPREAD

        # Order the edges by where their other end sits, so the lines leave in
        # the order they arrive and don't cross each other immediately
        for edges, ports, other in (
            (list(graph.out_edges(node)), leaving, 1),
            (list(graph.in_edges(node)), arriving, 0),
        ):
            edges.sort(key=lambda edge: positions[edge[other]][0])
            for i, edge in enumerate(edges):
                offset = (i + 1) / (len(edges) + 1) - 0.5
                ports[edge] = centre_x + offset * spread

    return leaving, arriving


def _row_gaps(positions, sizes):
    """Return the empty band between each pair of neighbouring rows.

    Args:
        positions (dict): The centre of each node's box.
        sizes (dict): The box size of each node.

    Returns:
        dict:
            A dictionary of the form {(lower_y, upper_y): (bottom, top)} giving
            the band each pair of rows leaves between them.
    """
    # Group the nodes into rows by the y they were placed at
    rows = {}
    for node, (_, y) in positions.items():
        rows.setdefault(round(y, 3), []).append(node)

    tops = {
        y: max(positions[n][1] + sizes[n][1] / 2.0 for n in nodes)
        for y, nodes in rows.items()
    }
    bottoms = {
        y: min(positions[n][1] - sizes[n][1] / 2.0 for n in nodes)
        for y, nodes in rows.items()
    }

    levels = sorted(rows)

    return {
        (lower, upper): (tops[lower], bottoms[upper])
        for lower, upper in zip(levels[:-1], levels[1:])
    }


def _edge_hops(edge, positions, routes, leaving, arriving):
    """Return the heights an edge passes through and the x of each, bottom up.

    Shared by the two passes over the edges, which would otherwise each build
    this and could drift apart. The arguments are the layout dictionaries
    documented on those callers.
    """
    levels = [positions[edge[0]][1]]
    levels.extend(y for _, y in routes.get(edge, []))
    levels.append(positions[edge[1]][1])

    xs = [leaving[edge]]
    xs.extend(x for x, _ in routes.get(edge, []))
    xs.append(arriving[edge])

    return levels, xs


def _edge_lanes(graph, positions, routes, leaving, arriving):
    """Give every sideways run of an edge its own height within its gap.

    Edges crossing the same pair of rows all turn in the same band. Running
    them all along the middle of it stacks them on top of each other, so each
    is given its own lane instead.

    Args:
        graph (networkx.DiGraph): The network.
        positions (dict): The centre of each node's box.
        routes (dict): The points each edge is routed through.
        leaving (dict): Where each edge leaves its source.
        arriving (dict): Where each edge arrives at its target.

    Returns:
        dict:
            A dictionary of the form {(edge, hop): y} giving the height each
            sideways run should happen at.
    """
    gaps = _row_gaps(positions, {node: (0.0, 0.0) for node in positions})

    # Collect the runs which need a lane, grouped by the band they cross
    runs = {}
    for edge in graph.edges:
        levels, xs = _edge_hops(edge, positions, routes, leaving, arriving)

        for hop in range(len(levels) - 1):
            # A run which doesn't move sideways has nothing to collide with
            if np.isclose(xs[hop], xs[hop + 1]):
                continue

            band = (levels[hop], levels[hop + 1])
            runs.setdefault(band, []).append(
                (edge, hop, (xs[hop] + xs[hop + 1]) / 2.0)
            )

    lanes = {}
    for band, band_runs in runs.items():
        # Order the runs across the band so neighbouring lanes belong to
        # neighbouring edges, which keeps them from crossing each other
        band_runs.sort(key=lambda run: (run[2], run[0]))

        bottom, top = gaps.get(band, band)
        height = top - bottom

        # Keep the lanes clear of the boxes on either side of the band
        margin = height * (1.0 - _LANE_SPAN) / 2.0
        low = bottom + margin
        span = height * _LANE_SPAN

        for i, (edge, hop, _) in enumerate(band_runs):
            fraction = (i + 1) / (len(band_runs) + 1)
            lanes[(edge, hop)] = low + fraction * span

    return lanes


def _attachment(outline, centre, reach, x, upward):
    """Return the point on an outline directly above or below a given x.

    Attaching an edge to the outline rather than to the box's bounding edge
    matters for the curved and scalloped shapes, where the two are not the same
    place.

    Args:
        outline (matplotlib.path.Path): The outline of the box.
        centre (tuple): The centre of the box, which is inside the outline.
        reach (float): How far to search from the centre.
        x (float): The horizontal position to attach at.
        upward (bool): Whether to attach to the top of the box or the bottom.

    Returns:
        tuple:
            The point on the outline.
    """
    direction = 1.0 if upward else -1.0

    # Walk out from the centre, which is inside, until we leave the outline
    inside, outside = centre[1], centre[1] + direction * reach
    for _ in range(14):
        middle = (inside + outside) / 2.0
        if outline.contains_point((x, middle)):
            inside = middle
        else:
            outside = middle

    return (x, inside)


def _edge_corners(edge, positions, routes, leaving, arriving, lanes, ends):
    """Return the corners an edge turns through, bottom to top.

    Args:
        edge (tuple): The edge.
        positions (dict): The centre of each node's box.
        routes (dict): The points each edge is routed through.
        leaving (dict): Where each edge leaves its source.
        arriving (dict): Where each edge arrives at its target.
        lanes (dict): The height each sideways run happens at.
        ends (tuple): The points on the two outlines the edge runs between.

    Returns:
        list:
            The corners of the route.
    """
    start, end = ends

    levels, xs = _edge_hops(edge, positions, routes, leaving, arriving)

    ys = [start[1]]
    ys.extend(y for _, y in routes.get(edge, []))
    ys.append(end[1])

    corners = [start]
    for hop in range(len(levels) - 1):
        lane = lanes.get((edge, hop))
        if lane is not None:
            corners.append((xs[hop], lane))
            corners.append((xs[hop + 1], lane))
        corners.append((xs[hop + 1], ys[hop + 1]))

    return corners


def _rounded_path(corners, radius):
    """Turn a list of corners into a path with rounded turns.

    Args:
        corners (list): The corners of the route, in order.
        radius (float): The corner radius, in points.

    Returns:
        matplotlib.path.Path:
            The path.
    """
    # Drop any zero length steps, which would otherwise produce stray corners
    trimmed = [corners[0]]
    for point in corners[1:]:
        if not (
            np.isclose(point[0], trimmed[-1][0])
            and np.isclose(point[1], trimmed[-1][1])
        ):
            trimmed.append(point)

    if len(trimmed) < 3:
        return Path(trimmed, [Path.MOVETO, Path.LINETO])

    # Round each corner with a quadratic curve, pulled back along both of its
    # legs by no more than half the shorter leg
    vertices = [trimmed[0]]
    codes = [Path.MOVETO]
    for i in range(1, len(trimmed) - 1):
        before = np.asarray(trimmed[i - 1], dtype=float)
        corner = np.asarray(trimmed[i], dtype=float)
        after = np.asarray(trimmed[i + 1], dtype=float)

        into = corner - before
        out_of = after - corner
        into_length = np.hypot(*into)
        out_length = np.hypot(*out_of)
        if into_length == 0.0 or out_length == 0.0:
            continue

        pull = min(radius, into_length / 2.0, out_length / 2.0)

        vertices.append(tuple(corner - into / into_length * pull))
        codes.append(Path.LINETO)
        vertices.append(tuple(corner))
        codes.append(Path.CURVE3)
        vertices.append(tuple(corner + out_of / out_length * pull))
        codes.append(Path.CURVE3)

    vertices.append(trimmed[-1])
    codes.append(Path.LINETO)

    return Path(vertices, codes)


def _draw_edges(ax, graph, positions, sizes, routes, fontsize):
    """Draw every dependency as an arrow.

    Args:
        ax (matplotlib.axes.Axes): The axis to draw on.
        graph (networkx.DiGraph): The network.
        positions (dict): The centre of each node's box.
        sizes (dict): The box size of each node.
        routes (dict): The points each edge should be routed through.
        fontsize (float): The font size the labels are drawn at.
    """
    radius = _CORNER * 2.0 * fontsize
    outlines = _node_outlines(graph, positions, sizes, fontsize)
    leaving, arriving = _edge_ports(graph, positions, sizes)
    lanes = _edge_lanes(graph, positions, routes, leaving, arriving)

    for source, target, data in graph.edges(data=True):
        edge = (source, target)

        # Emission flows upwards, so an edge leaves the top of its source and
        # enters the bottom of its target
        start = _attachment(
            outlines[source],
            positions[source],
            sizes[source][1],
            leaving[edge],
            upward=True,
        )
        end = _attachment(
            outlines[target],
            positions[target],
            sizes[target][1],
            arriving[edge],
            upward=False,
        )

        corners = _edge_corners(
            edge,
            positions,
            routes,
            leaving,
            arriving,
            lanes,
            (start, end),
        )

        ax.add_patch(
            mpatches.FancyArrowPatch(
                path=_rounded_path(corners, radius),
                arrowstyle="-|>",
                mutation_scale=max(fontsize * 0.85, 4.0),
                linestyle=_EDGE_STYLES[data["kind"]][0],
                linewidth=0.9,
                color=_INK,
                alpha=0.85,
                joinstyle="round",
                capstyle="round",
                zorder=1,
            )
        )


def _draw_nodes(ax, graph, positions, sizes, fontsize):
    """Draw every model as a labelled box.

    Args:
        ax (matplotlib.axes.Axes): The axis to draw on.
        graph (networkx.DiGraph): The network.
        positions (dict): The centre of each node's box.
        sizes (dict): The box size of each node.
        fontsize (float): The font size to draw the labels at.
    """
    for node, (x, y) in positions.items():
        data = graph.nodes[node]
        width, height = sizes[node]

        # Colour carries which emitter the model acts on
        if data["external"]:
            outline, fill = _EXTERNAL_COLORS
        else:
            outline, fill = _EMITTER_COLORS.get(
                data["emitter"],
                _EMITTER_COLORS["galaxy"],
            )

        # The fill carries whether the emission is kept. An empty box reads as
        # "nothing survives here" much more clearly than a faded one.
        facecolor = fill if data["save"] else _DISCARDED_FILL
        textcolor = _INK if data["save"] else _MUTED_INK

        # The reserved footprint also covers whatever the shape draws outside
        # its box and the offset copies of a stack, so the box is smaller
        box_width, box_height = _drawn_box(data, (width, height), fontsize)

        # The shape carries which operation the model performs
        boxstyle = _box_style(
            _shape_spec(data["operation"])["shape"],
            box_height,
            _TOOTH * fontsize,
        )

        # A dashed outline marks a mask, a dotted one a reused emission
        if data["is_masked"]:
            linestyle = (0, (3, 2))
        elif data["external"]:
            linestyle = (0, (1, 2))
        else:
            linestyle = "solid"

        # A per particle model holds an emission for every particle rather
        # than one for the whole component, which the stack of boxes behind it
        # marks. The copies sit down and to the right so the top stays clear
        # for the edges, and behind the box so the label is never drawn over.
        offset = _STACK_OFFSET * fontsize
        copies = _STACK_COPIES if data["per_particle"] else 0
        left = x - box_width / 2.0
        bottom = y - box_height / 2.0 + copies * offset

        for copy in range(copies, 0, -1):
            ax.add_patch(
                mpatches.FancyBboxPatch(
                    (left + copy * offset, bottom - copy * offset),
                    box_width,
                    box_height,
                    boxstyle=boxstyle,
                    facecolor=facecolor,
                    edgecolor=outline,
                    linewidth=1.1,
                    linestyle=linestyle,
                    zorder=2 - copy * 0.1,
                )
            )

        ax.add_patch(
            mpatches.FancyBboxPatch(
                (left, bottom),
                box_width,
                box_height,
                boxstyle=boxstyle,
                facecolor=facecolor,
                edgecolor=outline,
                linewidth=1.1,
                linestyle=linestyle,
                zorder=2,
            )
        )

        ax.text(
            x,
            bottom + box_height / 2.0,
            _node_text(graph, node),
            ha="center",
            va="center",
            color=textcolor,
            fontsize=fontsize,
            zorder=4,
        )


class _SwatchHandler(HandlerPatch):
    """Draw a legend swatch with the box shape it was given.

    Matplotlib's default patch handler builds a plain rectangle from the
    handle's colours, which silently discards the box style. That would leave
    the shapes in the legend indistinguishable from each other, and the shapes
    are how the legend explains which operation a box represents.
    """

    def create_artists(
        self,
        legend,
        orig_handle,
        xdescent,
        ydescent,
        width,
        height,
        fontsize,
        trans,
    ):
        """Build the artists which draw one legend swatch.

        Args:
            legend (matplotlib.legend.Legend): The legend being drawn.
            orig_handle (matplotlib.patches.FancyBboxPatch):
                The swatch to draw.
            xdescent (float): The horizontal offset of the swatch box.
            ydescent (float): The vertical offset of the swatch box.
            width (float): The width available to the swatch.
            height (float): The height available to the swatch.
            fontsize (float): The legend font size.
            trans (matplotlib.transforms.Transform):
                The transform to draw the swatch under.

        Returns:
            list:
                The artists making up the swatch.
        """
        shape = getattr(orig_handle, "_shape", "pill")
        stacked = getattr(orig_handle, "_stacked", False)

        # Leave room for the line width so the outline isn't clipped
        inset = 1.0
        origin = (-xdescent + inset, -ydescent + inset)
        size = (width - 2 * inset, height - 2 * inset)

        # A swatch is a different shape of box to a label, so the shape is
        # rebuilt against the swatch's own height
        boxstyle = _box_style(shape, size[1], size[1] * _SWATCH_TOOTH)

        artists = []

        # A stacked swatch says "many" with a single copy behind the front box.
        # Using as many copies as the boxes do would be a faithful scale model
        # and an unreadable one: each copy has to come out of the swatch's own
        # height, and two of them leave boxes shallower than the offsets
        # between them, which reads as a tangle rather than as a stack.
        copies = 1 if stacked else 0
        step = size[1] * 0.3
        origin = (origin[0], origin[1] + copies * step)

        # The swatches are otherwise drawn outline only, which for a stack
        # means every copy shows through every other one. Filling them with the
        # figure's own colour lets each copy hide the one behind it, so the
        # stack reads as a stack rather than as a tangle of outlines.
        opaque = None
        if stacked:
            opaque = legend.figure.get_facecolor()

        for copy in range(copies, 0, -1):
            behind = mpatches.FancyBboxPatch(
                (origin[0] + copy * step, origin[1] - copy * step),
                size[0] - copies * step,
                size[1] - copies * step,
                boxstyle=boxstyle,
            )
            self.update_prop(behind, orig_handle, legend)
            if opaque is not None:
                behind.set_facecolor(opaque)
            behind.set_transform(trans)
            artists.append(behind)

        outer = mpatches.FancyBboxPatch(
            origin,
            size[0] - copies * step,
            size[1] - copies * step,
            boxstyle=boxstyle,
        )
        self.update_prop(outer, orig_handle, legend)
        if opaque is not None:
            outer.set_facecolor(opaque)
        outer.set_transform(trans)
        artists.append(outer)

        return artists


def _draw_legends(ax, groups, shape, widths, fontsize):
    """Draw the legend groups, in a band above and a band below the network.

    The axis is in points, so the groups can be placed by measuring rather
    than by guessing at axis fractions: each is given exactly the width it
    needs, and each band is centred over the network.

    Args:
        ax (matplotlib.axes.Axes): The axis to draw on.
        groups (dict): The legend entries, grouped by title.
        shape (dict): How many columns and rows each group is drawn in.
        widths (dict): The width each group needs, in units of the font size.
        fontsize (float): The font size to draw the legends at.
    """
    xmin, xmax = ax.get_xlim()
    axis_width = xmax - xmin

    # The last legend drawn becomes the axis's own, which is where anything
    # asking for "the" legend looks. Every other one has to be kept explicitly,
    # since drawing another would replace it.
    drawn = []

    for band, anchor, loc in (
        ("top", 1.0, "upper left"),
        ("bottom", 0.0, "lower left"),
    ):
        titles = [
            title
            for title in groups
            if _LEGEND_PLACEMENT.get(title, "top") == band
        ]
        if len(titles) == 0:
            continue

        # Centre this band's groups over the network
        block = sum(widths[title] for title in titles) * fontsize
        block += _LEGEND_GROUP_SPACING * fontsize * (len(titles) - 1)
        left = (axis_width - block) / 2.0

        for title in titles:
            legend = ax.legend(
                handles=groups[title],
                title=title,
                loc=loc,
                frameon=False,
                bbox_to_anchor=(left / axis_width, anchor),
                ncol=shape[title][0],
                fontsize=fontsize,
                labelcolor=_INK,
                handlelength=_LEGEND_HANDLE,
                handleheight=_LEGEND_HANDLE_HEIGHT,
                handletextpad=_LEGEND_TEXT_PAD,
                columnspacing=_LEGEND_COLUMN_SPACING,
                borderpad=_LEGEND_BORDER_PAD,
                borderaxespad=0.0,
                handler_map={mpatches.FancyBboxPatch: _SwatchHandler()},
            )
            legend.set_title(
                title,
                prop={"size": fontsize, "weight": "bold"},
            )
            legend.get_title().set_color(_INK)
            drawn.append(legend)

            left += (widths[title] + _LEGEND_GROUP_SPACING) * fontsize

    for legend in drawn[:-1]:
        ax.add_artist(legend)


def plot_emission_graph(
    model_tree,
    root=None,
    show=True,
    fontsize=10,
    figsize=None,
    layout="layered",
    show_variants=False,
    min_fontsize=_MIN_FONTSIZE,
):
    """Plot the network of models defining an emission.

    The whole network is drawn, including related models, which are roots in
    their own right. It reads bottom to top, in the direction the emission
    flows, with each model sitting below whatever consumes it.

    Args:
        model_tree (EmissionModel): The model whose network is being drawn.
        root (str):
            If given, only this model and the models it depends on are drawn.
        show (bool): Whether to show the plot.
        fontsize (int):
            The fontsize to use for the labels. This is reduced if the network
            doesn't fit the figure.
        figsize (tuple):
            The size of the figure to plot (width, height). By default the
            figure is sized to fit the network.
        layout (str):
            Either "layered" (the default), which needs only networkx, or
            "dot", which lays the network out with graphviz and needs pydot and
            the graphviz binary.
        show_variants (bool):
            Whether to draw every parameter variant as its own node. By
            default each family of variants is collapsed into a single node
            badged with the number of models it stands for, since an expansion
            of any size produces more models than can be read at once. This
            has no effect on a model which was never expanded.
        min_fontsize (float):
            The size below which labels stop being readable. A network which
            cannot fit the figure with labels this big grows the figure rather
            than shrinking them further, so a big network stays as readable
            as a small one. Pass 0 to let the labels shrink as far as needed.

    Returns:
        fig (matplotlib.figure.Figure): The figure containing the plot.
        ax (matplotlib.axes.Axes): The axis containing the plot.
    """
    graph = _build_graph(
        model_tree,
        root=root,
        show_variants=show_variants,
    )

    # Work out the legends first, since they need room above the network
    groups = _legend_groups(graph)
    shape = _legend_shape(groups)
    group_widths, legend_width, legend_rows = _legend_bands(groups, shape)

    positions, sizes, routes, fontsize, figsize, limits = _fit(
        graph,
        layout,
        fontsize,
        figsize,
        legend_width,
        legend_rows,
        min_fontsize,
    )

    fig = plt.figure(figsize=figsize)

    # One axis filling the figure, with limits in points, so a data unit is a
    # point and the boxes are exactly the size the layout assumed
    ax = fig.add_axes([0.0, 0.0, 1.0, 1.0])
    ax.set_xlim(limits[0], limits[1])
    ax.set_ylim(limits[2], limits[3])
    ax.axis("off")

    _draw_edges(ax, graph, positions, sizes, routes, fontsize)
    _draw_nodes(ax, graph, positions, sizes, fontsize)

    _draw_legends(
        ax,
        groups,
        shape,
        group_widths,
        max(fontsize, _MIN_LEGEND_FONTSIZE),
    )

    if show:
        plt.show()

    return fig, ax
