"""Golden full-pipeline regression tests.

Unlike the rest of the suite -- which mostly checks individual pieces of
physics against an analytic or quadrature reference -- this module pins the
output of the *whole* particle -> grid-weighted spectra -> combination ->
dust attenuation -> integration -> observed-flux pipeline for a small, fixed
stellar population against a stored reference. The reference values live in
``tests/data/golden_pipeline_reference.npz`` and were generated by
``tests/data/create_golden_pipeline_reference.py``.

Its job is to catch *accidental* numeric drift introduced anywhere along
that pipeline -- exactly the kind of regression a large refactor (e.g. the
precision templating of the C++ extensions) could introduce without any
individual unit test noticing. If a change is expected to alter these
numbers, regenerate the reference with the script above and explain why in
the commit message; don't just loosen the tolerance.
"""

from pathlib import Path

import numpy as np
import pytest
from astropy.cosmology import Planck18
from unyt import Mpc, Myr, unyt_array

from synthesizer.emission_models import PacmanEmission
from synthesizer.emission_models.transformers import PowerLaw
from synthesizer.grid import Grid
from synthesizer.particle.stars import Stars

REFERENCE_PATH = (
    Path(__file__).parent / "data" / "golden_pipeline_reference.npz"
)


@pytest.fixture
def golden_reference():
    """Load the stored golden-pipeline reference arrays."""
    with np.load(REFERENCE_PATH) as data:
        return {key: data[key] for key in data.files}


def _build_golden_stars(dtype):
    """Build the fixed deterministic stellar population at ``dtype``.

    Mass is built via the ``unyt_array(data, "Msun")`` constructor rather
    than the more common ``data * Msun`` idiom: multiplying a float32 array
    by the ``Msun`` unit silently upcasts it to float64 (a unyt quirk
    specific to ``Msun``, traced back to its physical-constant-backed scale
    factor -- ``Mpc``, ``Myr`` and other units used elsewhere in this file
    do not do this). Using ``data * Msun`` here would make the "float32"
    pipeline below silently run its mass weighting in float64.
    """
    return Stars(
        initial_masses=unyt_array(
            np.array([1.0e6, 2.5e6, 1.2e6, 3.0e6, 0.8e6], dtype=dtype),
            "Msun",
        ),
        ages=np.array([3.0e6, 1.0e7, 5.0e7, 2.0e8, 1.0e9], dtype=dtype) * Myr,
        metallicities=np.array([0.001, 0.004, 0.01, 0.02, 0.03], dtype=dtype),
        redshift=5.0,
        coordinates=np.zeros((5, 3), dtype=dtype) * Mpc,
    )


def _run_golden_pipeline(test_grid, dtype, out_dtype):
    """Run the fixed golden pipeline and return (sed, fnu)."""
    stars = _build_golden_stars(dtype)
    model = PacmanEmission(
        test_grid,
        tau_v=0.5,
        dust_curve=PowerLaw(slope=-1.0),
        fesc=0.1,
        fesc_ly_alpha=0.5,
    )
    sed = stars.get_spectra(model, out_dtype=out_dtype)
    fnu = sed.get_fnu(Planck18, z=5.0, out_dtype=out_dtype)
    return sed, fnu


class TestGoldenPipelineRegression:
    """Pin the full stellar pipeline output against a stored reference."""

    def test_float64_pipeline_matches_golden_reference(
        self, test_grid, golden_reference
    ):
        """The float64 pipeline should exactly reproduce the reference."""
        sed, fnu = _run_golden_pipeline(
            test_grid, np.float64, out_dtype=np.float64
        )

        np.testing.assert_allclose(
            sed.lam.to("angstrom").value, golden_reference["lam"]
        )
        np.testing.assert_allclose(
            sed.lnu.to("erg/s/Hz").value,
            golden_reference["lnu"],
            rtol=1e-9,
            atol=0.0,
        )
        np.testing.assert_allclose(
            fnu.to("nJy").value,
            golden_reference["fnu"],
            rtol=1e-9,
            atol=0.0,
        )
        np.testing.assert_allclose(
            sed.bolometric_luminosity.to("erg/s").value,
            golden_reference["bolometric_luminosity"],
            rtol=1e-9,
            atol=0.0,
        )

    def test_float32_pipeline_matches_golden_reference(self, golden_reference):
        """The float32 pipeline should stay close to the float64 reference.

        This is the sharpest end-to-end check that the adaptive-precision
        work actually gets the right answer: running the identical physical
        setup entirely in float32 (particles, grid weighting, spectra
        combination, attenuation, integration, and the observed-flux
        conversion) should reproduce the float64 golden reference to within
        float32 rounding, not accumulate drift along the way.
        """
        # Particle and grid arrays must share a dtype family (Synthesizer
        # never casts behind the scenes), so load a float32 copy of the
        # grid to pair with the float32 particle data below.
        grid32 = Grid("test_grid.hdf5", use_precision=np.float32)

        sed, fnu = _run_golden_pipeline(
            grid32, np.float32, out_dtype=np.float32
        )

        assert sed._lnu.dtype == np.float32
        assert sed._fnu.dtype == np.float32

        np.testing.assert_allclose(
            sed.lnu.to("erg/s/Hz").value,
            golden_reference["lnu"],
            rtol=2e-3,
            atol=1e-3 * np.abs(golden_reference["lnu"]).max(),
        )
        np.testing.assert_allclose(
            fnu.to("nJy").value,
            golden_reference["fnu"],
            rtol=2e-3,
            atol=1e-3 * np.abs(golden_reference["fnu"]).max(),
        )
        np.testing.assert_allclose(
            sed.bolometric_luminosity.to("erg/s").value,
            golden_reference["bolometric_luminosity"],
            rtol=1e-5,
        )
