CMB: false  # include CMB heating
T_floor: 100  # lower gas temperature floor
U_model: ref  # which ionisation parameter model to use. `ref` assumes a varying ionisation parameter at a fixed reference age and metallicity
log10U_ref: -2  # value of ionisation parameter at reference value, for U_model='ref'
log10age_ref: 6.0  # log10(age/year) at which to set reference ionisation parameter, for U_model='ref'
Z_ref: 0.01  # metallicity at which to set reference ionisation parameter, for U_model='ref'
alpha: 0.0  # alpha element enhancement
CO: 0.0  #
cloudy_version: v17.03
cosmic_rays: false  # flag for inclusion of cosmic ray heating
covering_factor: 1.0  #
d2m: 0.3  # dust to metals ratio in the cloud
log10n_H: 2  # log hydrogen density
log10radius: -2  # log of the radius of the cloud, in parsecs
scaling: null
stop_T: 4000  # stopping temperature
stop_efrac: -2  # limiting ratio of electron to H densities
z: 0.0  # redshift
geometry: spherical
grains: true # include grains
resolution: 1.0 # energy resolution relative to the default