name: Publish Python Package

on:
  push:
    tags:
      - "v*.*.*" # Matches version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    # Grant the job permission to request an OIDC token
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools-scm

      - name: Build source distribution (sdist only)
        run: python -m build --sdist

      # We publish using the "Trusted Publisher" system on PyPi
      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@v1.6.0
        with:
          user: __token__
