# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Synthesizer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
        # Install google API for downloading test data
        pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client gdown
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude broken_examples
    - name: Download test data
      env:
          GOOGLE_DRIVE_CLIENT_SECRET: ${{ secrets.GOOGLE_DRIVE_CLIENT_SECRET }}
      run: |
        gdown https://drive.google.com/uc?id=1txY9PY-ejtRaMSZorpZSxGPsm6muvh9X&confirm=t --output tests/test_grid/test_grid.hdf5
        gdown https://drive.google.com/uc?id=1WkQQ1s3uh9lmx1Ye6RlM9qhrxcWp5N87&confirm=t --output tests/test_grid/test_grid_blackholes.hdf5
    - name: Test with pytest
      run: |
        pytest
        pytest --nbmake docs/source/*.ipynb docs/source/*/*.ipynb
    - name: Sphinx Build
      run: |
        cd docs
        sudo apt install pandoc
        pip install -r requirements.txt
        make clean
        make html
